# Generated by Django 3.2 on 2022-06-12 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('1', 'فروردین'), ('2', 'اردیبهشت'), ('3', 'خرداد'), ('4', 'تیر'), ('5', 'مرداد'), ('6', 'شهریور'), ('7', 'مهر'), ('8', 'آبان'), ('9', 'آذر'), ('10', 'دی'), ('11', 'بهمن'), ('12', 'اسفند')], max_length=2)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='days.year')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('chand_shanbe', models.CharField(choices=[('ش', 'شنبه'), ('ی', 'یک شنبه'), ('د', 'دو شنبه'), ('س', 'سه شنبه'), ('چ', 'چهار شنبه'), ('پ', 'پنج شنبه'), ('ج', 'جمعه')], max_length=1)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='days.month')),
            ],
        ),
    ]
